databases:
  - name: my-room-django
    databaseName: my_room_django
    user: my_room_django

services:
  - type: web
    name: my_room_django
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn my_room_django.wsgi"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_room_django
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4