# Generated by Django 4.1b1 on 2022-07-14 10:56

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('location_id', models.PositiveBigIntegerField()),
                ('price_from', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_avg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stars', models.IntegerField()),
                ('country', models.CharField(max_length=150)),
                ('state', models.CharField(blank=True, max_length=150, null=True)),
                ('place', models.CharField(max_length=150)),
                ('geo_lond', models.DecimalField(decimal_places=6, max_digits=9)),
                ('geo_lat', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='HotelPhoto',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='hotel-photos')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='hotel.hotel')),
            ],
        ),
    ]
